for i in range(1, 11):
    print(i)




for i in range(2, 21, 2):
    print(i)






n = int(input("შეიყვანე რიცხვი n: "))
sum = 0

for i in range(1, n + 1):
    sum += i

print("რიცხვების ჯამი 1-დან", n, "-მდე არის:", sum)










for i in range(10, 0, -1):
    print(i)









i = 1
sum = 0

while i <= 100:
    if i % 2 != 0:
        sum += i
    i += 1

print("კენტ რიცხვთა ჯამი 1-დან 100-მდე არის:", sum)











for i in range(1, 11):
    print(i)







for i in range(2, 21, 2):
    print(i)










n = int(input("შეიყვანე რიცხვი n: "))
sum = 0

for i in range(1, n + 1):
    sum += i

print("1-დან", n, "-მდე რიცხვების ჯამი არის:", sum)









for i in range(10, 0, -1):
    print(i)












sum = 0

for i in range(1, 101):
    if i % 2 != 0:
        sum += i

print("1-დან 100-მდე კენტ რიცხვთა ჯამი არის:", sum)



